### ISSUE TITLE
Breaking with Vuetify Loader 1.6

### ISSUE THREAD

**Issue by stephenjason89** [Nothing-Works/vuetifyjs-mix-extension#13]
It has errors on building when I upgraded to vuetify loader 1.6

here's a link to the original issue with the fix for laravel mix

https://github.com/vuetifyjs/vuetify-loader/issues/144

would be really nice if you can implement it here

Thank you

**Comment by Nothing-Works** [comment]
`0.0.11` should fix this issue.

**Comment by Nothing-Works** [comment]
can you let me know any other problem you have as well? thanks.

**Comment by stephenjason89** [comment]
That was fast, I just tried it now but getting a lot of errors.
This was after upgrading from v 0.0.9 to 0.0.11
and vuetify loader 1.5 to 1.6
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
ValidationError: Invalid options object. Sass Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'additionalData'. These properties are valid:
   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }
    at validate (C:\Development\Web Projects\Foodat\node_modules\schema-utils\dist\validate.js:88:11)
    at Object.loader (C:\Development\Web Projects\Foodat\node_modules\sass-loader\dist\index.js:36:28)



and 


Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
ValidationError: Invalid options object. Sass Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'additionalData'. These properties are valid:
   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }
    at validate (C:\Development\Web Projects\Foodat\node_modules\schema-utils\dist\validate.js:88:11)
    at Object.loader (C:\Development\Web Projects\Foodat\node_modules\sass-loader\dist\index.js:36:28)

 @ ./node_modules/vuetify/src/components/VDivider/VDivider.sass 4:14-124
 @ ./node_modules/vuetify/lib/components/VDivider/VDivider.js
 @ ./node_modules/vuetify/lib/components/VDivider/index.js
 @ ./resources/assets/js/pages/Dashboard.vue
 @ ./resources/assets/js/routes.js
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js



Thank you :)

**Comment by Nothing-Works** [comment]
@stephenjason89 can you update `sass-loader` to the latest version or at least `^9.0.0`. That should fix it.

**Comment by stephenjason89** [comment]
Thank you everything is working now :)
Why didn't npm update command updated my sass loader from ^8.0.* to ^9.0
