### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by stephenjason89** [Nothing-Works/vuetifyjs-mix-extension#15]
It seems like safari browser doesn't render it properly.

I tried
https://vuetifyjs.com/en/getting-started/browser-support/

Please let me know how this can be applied.
Babel polyfill gives me tons of errors on building as well

**Comment by Nothing-Works** [comment]
What version of safari are you having problems? What's the problem? Do you have any errors? This is just an extension that should have nothing to do with the browser support (in theory). Please be more specific when you fire an issue.

**Comment by stephenjason89** [comment]
Sorry about that. 
Was using safari 10, the issue was node_modules are not being transpiled by babel.
I had to add this
    .webpackConfig({
        module: {
            rules: [{
                test: /\.jsx?$/,
                use: [{
                    loader: 'babel-loader',
                    options: Config.babel()
                }]
            }]
        },
}

on my webpack.mix.js

Maybe you can include an option for this in the package since laravel opt to not transpile node_modules folder.
