### ISSUE TITLE
how to enable progressive images? is possible?

### ISSUE THREAD

**Issue by LucaColombi** [Nothing-Works/vuetifyjs-mix-extension#2]
hello, would be great to have a way to enable progressive images, like shown here:

https://github.com/vuetifyjs/vuetify-loader#progressive-images

is it possible? how? or can you enable it as some kind of option?

**Comment by Nothing-Works** [comment]
@LucaColombi this is a good point and seems easy to add. Will let you know once I've done.

**Comment by Nothing-Works** [comment]
@LucaColombi can you update to 0.0.3 and [here](https://github.com/Nothing-Works/vuetifyjs-mix-extension#progressive-images) is how to use it. Can you also help me to test it? Would like to hear your feedback.

**Comment by Nothing-Works** [comment]
@LucaColombi I will close this, if you have any issue feel free to discuss on this thread.
