### ISSUE TITLE
Support Laravel Mix 6

### ISSUE THREAD

**Issue by alekbless** [Nothing-Works/vuetifyjs-mix-extension#20]
Is this supported with the new Laravel Mix 6 w/Webpack 5?

**Comment by Tim-Frensch** [comment]
Not really right now it seems. I've been trying to get this to work without errors. Even downgrading to other laravel mix versions didn't seem to work.

vuetify-loader gives a `Error: Cannot find module 'webpack/lib/RuleSet'.`

I got it to work without tree-shaking but not really sure if it's supposed to work like this.
`mix.js('resources/js/app.js', 'public/js').vue().vuetify()`

**Comment by alekbless** [comment]
I was able to get this working. Upgraded to Laravel Mix 6 and Vuetify Loader 1.7.1. 

Did you install the latest vuetify-loader supporting webpack 5? 

`vuetify-loader@next`

**Comment by Tim-Frensch** [comment]
Hmm, that gives me this error ` Error: [VuetifyLoaderPlugin Error] No matching rule for vue-loader found.
`
Do you mind sharing your webpack.mix.js so i can see what i am doing wrong?

**Comment by alekbless** [comment]
The new .vue "featured flag" in mix needs to be loaded after vuetify. 

```
mix
  .js('resources/js/app.js', 'public/js')
  .vuetify('vuetify-loader')
  .vue({ version: 2 });
```

**Comment by Tim-Frensch** [comment]
That did the trick. Thank you very much.

**Comment by alekbless** [comment]
@Tim-Frensch Great! 

Seems to run fine for me so far.

**Comment by Nothing-Works** [comment]
@Tim-Frensch @alekbless will try to support v6 by this weekend. Thanks for your patience.

**Comment by Nothing-Works** [comment]
@Tim-Frensch @alekbless have a read of this https://github.com/Nothing-Works/vuetifyjs-mix-extension#known-issue-for-existing-plugin-users-26012021 as long as the 'vuetify-loader' is `^1.7.1` you should be all good. I also updated the docs for mix version 6. feel free to reopen or discuss this if you still have problems.
