### ISSUE TITLE
No vuetify component is registered

### ISSUE THREAD

**Issue by Frozire** [Nothing-Works/vuetifyjs-mix-extension#4]
When I follow the installation in a clean Laravel installation with the Vue preset, I am still not able to use any Vuetify component.

What is the missing step?

The console is just full of "did you register the component correctly?" - Do you have a sample repo with it running?

**Comment by Frozire** [comment]
I found your own repo implementing it - I was missing this file.

https://github.com/Nothing-Works/mix/blob/master/resources/js/plugin.js

**Comment by Nothing-Works** [comment]
@Frozire  it's nice you've found the missing plugin. there are some [instructions](https://github.com/Nothing-Works/vuetifyjs-mix-extension/blob/master/laravel.md) for `Laravel` projects.
