### ISSUE TITLE
How to enable tree shaking?

### ISSUE THREAD

**Issue by stephenjason89** [Nothing-Works/vuetifyjs-mix-extension#5]
Great work btw,
I keep on having to manually declare all the components that i need

```
import Vuetify, {VLayout, VApp, VAppBar, . . .} from 'vuetify/lib';
import 'vuetify/dist/vuetify.min.css';

Vue.use(Vuetify, {
    components: {VLayout, VApp, VAppBar},
});

const opts = {}
let vuetify = new Vuetify(opts);
```

would it be possible to just do it like this?

```
import Vuetify from 'vuetify/lib';
import 'vuetify/dist/vuetify.min.css';

Vue.use(Vuetify);

const opts = {}
let vuetify = new Vuetify(opts);
```

and let vue-loader do the auto tree shaking?

Thank you for your work!

**Comment by Nothing-Works** [comment]
```js
mix.js('resources/js/app.js', 'public/js').vuetify('vuetify-loader')
```
```js
// src/plugins/vuetify.js

import Vue from 'vue'
import Vuetify from 'vuetify/lib'

Vue.use(Vuetify)

const opts = {}

export default new Vuetify(opts)
```

**Comment by stephenjason89** [comment]
Thank you for the reply sir.
I actually did that before and for some weird reason it was not working using 
import Vuetify from 'vuetify/lib'

but I don't know what happened it started working now.
I just tried it again.

Thank you so much I might have done something wrong which i didn't notice before.

**Comment by Nothing-Works** [comment]
@stephenjason89 this should work no matter what command you are running, if you still have problems send minimum code to reproduce it so I can have a look.

**Comment by stephenjason89** [comment]
Thank you again for the prompt reply. 
I figured it out.

I thought i can make V-app a wrapper so i put an id of vue
then create a new Vue on el:vue

```
@extends('layouts.default')

@section('content')
{{--check routes.js for default view of / --}}
    <v-app id="vue">
        <router-view></router-view>
    </v-app>
@endsection
```

This was the reason it was behaving strangely.

I just wrapped it in a div now and use V-app inside the vue templates.
```
@extends('layouts.default')

@section('content')
{{--check routes.js for default view of / --}}
    <div id="vue">
        <router-view></router-view>
    </div>
@endsection
```

Thank you!

**Comment by Nothing-Works** [comment]
@stephenjason89 good, I will close this then.

**Comment by stephenjason89** [comment]
I'm sorry to ask, where do i put my style/variables.scss?

```
-assets
--js
----components
----pages
----app.js
--styles   <-----should it be here or inside js folder?
----variables.scss
```

Thank you again

**Comment by Nothing-Works** [comment]
@stephenjason89  by default, it does not require any `css` or `scss`. If you want to use your own `css`, that's completely up to you, as long as you reference it right.

**Comment by stephenjason89** [comment]
I've been trying to make it work using that file structure and putting this inside a component

```
<style lang="scss">
    @import './resources/assets/styles/variables.scss';
</style>
```

it is not working :(

**Comment by Nothing-Works** [comment]
@stephenjason89 are you talking about this [section](https://vuetifyjs.com/en/customization/sass-variables/)?

**Comment by stephenjason89** [comment]
Yes sir. I've been trying it out.
Testing all vuetify features.

**Comment by Nothing-Works** [comment]
@stephenjason89 see this issue here https://github.com/Nothing-Works/vuetifyjs-mix-extension/issues/6

**Comment by stephenjason89** [comment]
Thanks, I guess I won't be using variables file for now 😁

**Comment by Nothing-Works** [comment]
@stephenjason89 the latest version should solve https://github.com/Nothing-Works/vuetifyjs-mix-extension/issues/6, if you still have issues please let's discuss in that thread.
