### ISSUE TITLE
Can I extract vue ?

### ISSUE THREAD

**Issue by david890517** [Nothing-Works/vuetifyjs-mix-extension#7]
Hi Sir,
If I extract the vue , then  vue is not working  to load .

`mix.js('resources/assets/js/app.js', 'public/js').extract([
    'vue',
])
`

**Comment by Nothing-Works** [comment]
@david890517 you are not using `vuetifyjs-mix-extension` at all. You should not fire an issue here.

**Comment by david890517** [comment]
> @david890517 you are not using `vuetifyjs-mix-extension` at all. You should not fire an issue here.
ok,thank you for the quick reply.
