### ISSUE TITLE
Icons from vuetify dont work.

### ISSUE THREAD

**Issue by emptyhere** [Nothing-Works/vuetifyjs-mix-extension#8]
I migrate some views to my laravel project and icons just gone.

**Comment by emptyhere** [comment]
js/plugins/vuetify js

```
import Vue from 'vue'
import Vuetify from 'vuetify'
import 'vuetify/dist/vuetify.min.css'
import 'material-design-icons-iconfont/dist/material-design-icons.css'

Vue.use(Vuetify)

const opts = {
  icons: {
    iconfont: 'mdiSvg' // 'mdi' || 'mdiSvg' || 'md' || 'fa' || 'fa4' || 'faSvg'
  }
}

export default new Vuetify(opts)

```

This helps, but not in all cases.

**Comment by emptyhere** [comment]
Solved.

**Comment by Nothing-Works** [comment]
@emptyhere Hi, can I know what's causing this? is there something I can improve from the plugin level?

**Comment by emptyhere** [comment]
> 
> 
> @emptyhere Hi, can I know what's causing this? is there something I can improve from the plugin level?

Sry, idk. If i find the main source of the problem I will let you know.
